/** Tailwind config — Agent//Core design system (from the Stitch design). */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#55433d",
        "inverse-surface": "#2f312e",
        "surface": "#F3F0E7",
        "surface-dim": "#DAD5C7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#FAF8F1",
        "surface-container": "#F0ECDF",
        "surface-container-high": "#EAE5D6",
        "surface-container-highest": "#E3DDCC",
        "primary": "#9E4B2F",
        "primary-container": "#B4593A",
        "on-primary": "#ffffff",
        "outline": "#8A7E6C",
        "light-bg": "#F3F0E7",
        "light-surface": "#FFFFFF",
        "light-border": "#E6E0D0",
        "light-text": "#211E18",
        "light-muted": "#837A69",
        "dark-bg": "#191713",
        "dark-surface": "#221F19",
        "dark-border": "#332E26",
        "dark-text": "#ECE6D9",
        "accent-terracotta": "#B4593A",
        "accent-deep": "#9E4B2F",
        // warm "cloud" sidebar tone (a touch lighter/cleaner than the cream canvas)
        "claude-sidebar": "#FAF8F1",
        "claude-sidebar-dark": "#211E19",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", "2xl": "1rem", full: "9999px" },
      spacing: { "sidebar-width": "260px", "panel-width": "var(--panel-w, 340px)", gutter: "24px" },
      fontFamily: {
        // UI chrome (sidebar, buttons, headings) = clean sans; chat replies = reading serif.
        "body-ui": ["Inter", "system-ui", "sans-serif"],
        "display": ["Inter", "system-ui", "sans-serif"],
        "headline": ["Inter", "system-ui", "sans-serif"],
        "body-prose": ["Newsreader", "Georgia", "serif"],
        "code": ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [],
};
