/** Tailwind config — Agent//Core design system (from the Stitch design). */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#55433d",
        "inverse-surface": "#2f312e",
        "surface": "#faf9f5",
        "surface-dim": "#dbdad6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f0",
        "surface-container": "#efeeea",
        "surface-container-high": "#e9e8e4",
        "surface-container-highest": "#e3e2df",
        "primary": "#99462a",
        "primary-container": "#d97757",
        "on-primary": "#ffffff",
        "outline": "#88726c",
        "light-bg": "#FAF9F5",
        "light-surface": "#FFFFFF",
        "light-border": "#E8E5DD",
        "light-text": "#1A1A18",
        "light-muted": "#6B6862",
        "dark-bg": "#1F1E1D",
        "dark-surface": "#262624",
        "dark-border": "#3A3833",
        "dark-text": "#ECEAE3",
        "accent-terracotta": "#D97757",
        "accent-deep": "#BD5D40",
        // Claude-style warm "cloud" sidebar tone (a touch warmer than the canvas)
        "claude-sidebar": "#F0EEE6",
        "claude-sidebar-dark": "#1A1917",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", "2xl": "1rem", full: "9999px" },
      spacing: { "sidebar-width": "260px", "panel-width": "340px", gutter: "24px" },
      fontFamily: {
        "body-ui": ["Inter", "system-ui", "sans-serif"],
        "display": ["Geist", "Inter", "system-ui", "sans-serif"],
        "headline": ["Geist", "Inter", "system-ui", "sans-serif"],
        "body-prose": ["'Source Serif 4'", "Georgia", "serif"],
        "code": ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [],
};
